### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by francescoagati** [andrewosh/hyperbeedown#1]
hi,
there is a gist with an example code for use this wrapper?
thanks

**Comment by andrewosh** [comment]
Hi @francescoagati, 

This repo currently depends on some changes to hyperdb that haven't been merged yet, so it's still very much a work in progress. I'll make sure to update the README to make this clearer -- once it's functional I'll add more documentation.

**Comment by andrewosh** [comment]
Updated the README. Thanks for opening the issue.

**Comment by francescoagati** [comment]
ok thanks for the fast reply
