### ISSUE TITLE
your fork of abstract-leveldown

### ISSUE THREAD

**Issue by ralphtheninja** [andrewosh/hyperbeedown#2]
Interesting project! I noticed you forked `abstract-leveldown` because you need to pass in an `options` object to your tests, is there anything we can do to tweak in upstream to help you out?

I couldn't create an issue on the fork so posted here. Hope that's ok :)

**Comment by andrewosh** [comment]
Hey @ralphtheninja!

Glad you like it :) Yeah I definitely wasn't planning on keeping the fork -- just needed to make the changes quickly to get my tests working. Think this approach is reasonable for a PR? If so, I'll throw that together tonight.

**Comment by ralphtheninja** [comment]
> Think this approach is reasonable for a PR? If so, I'll throw that together tonight.

Not sure yet. I have to sleep on it :smile: 

cc @vweevers

**Comment by vweevers** [comment]
Strictly speaking it means `hyperdown` isn't `abstract-leveldown` compliant. No other implementations have required options in `open(options)` - *edit: that I know of; SQL implementations might*.

Is it possible to instead have sane defaults (for the `map` and `reduce` options)?

**Comment by vweevers** [comment]
Or perhaps pass such options to the constructor instead. Then you might be able to use `testCommon` to create db's for tests.

**Comment by andrewosh** [comment]
@vweevers Indeed I've thought about that too. It's definitely possible to have a noop `map` and a `reduce` that just selects the first element from the conflict list. That said, I'm not sure I want to hide the fact that conflicts are both possible and expected (and thus you'll want to put thought into a meaningful `reduce`). 

Having a "select the first element" `reduce` as the default will lead to confusing issues in many non-test settings. It will also be used by most, as people tend to stick with sane defaults. The combination of those two things...

Are there other examples of `abstract-leveldowns` that have been built over a storage system where conflicts are the norm?

When this module is ready for use, I'll make sure this is all explicitly documented in the readme.

**Comment by vweevers** [comment]
I see your point.

> Are there other examples of abstract-leveldowns that have been built over a storage system where conflicts are the norm?

Maybe https://github.com/nlf/riakdown

**Comment by andrewosh** [comment]
Oh, referring to your previous comment, I was under the impression that the constructor can't take any options beyond `location`, so any additional config has to go through `open`!  This could certainly be handled in the constructor if that's not true. 

Edit: As in, existing consumers of `abstract-leveldown` would only expect to provide configuration through `open`.

**Comment by vweevers** [comment]
> Oh, referring to your previous comment, I was under the impression that the constructor can't take any options beyond location, so any additional config has to go through open! This could certainly be handled in the constructor if that's not true.

You're not wrong (in the context of the abstract test suite). We're working towards making `location `optional though. As part of that effort, we could consider even more freedom. Memdown for example, doesn't have a `location` and currently passes an empty string to `abstract-leveldown` to avoid it throwing. 

Can't hurt to think out loud, to find the best generic solution.

**Comment by vweevers** [comment]
Here's an example of an implementation that takes options in the ctor: https://github.com/Level/encoding-down/blob/6ada76e5d0befcb7e4f535e2fa2a7d1e77e5c111/index.js#L13-L23

**Comment by vweevers** [comment]
@ralphtheninja how do you feel about refactoring the test suite to use a `testCommon.factory` function, which would return a `db`, and allows implementations to add options etc?

**Comment by ralphtheninja** [comment]
> @ralphtheninja how do you feel about refactoring the test suite to use a testCommon.factory function, which would return a db, and allows implementations to add options etc?

I think we need to do _something_ to make it more generic and `testCommon.factory` might be one way to do it. I don't have the code in my head right now.

**Comment by andrewosh** [comment]
@vweevers Thanks for those links -- I'd looked for examples of that pattern before but couldn't find any. `testCommon.factory` assumes moving towards constructor options right? 

Now it's my turn to sleep on this :) Happy to move this conversation over to the abstract-leveldown repo too if y'all want to get more eyes on this discussion.

**Comment by vweevers** [comment]
> testCommon.factory assumes moving towards constructor options right?

Yep.

> Now it's my turn to sleep on this :) Happy to move this conversation over to the abstract-leveldown repo too if y'all want to get more eyes on this discussion.

👍

**Comment by ralphtheninja** [comment]
@vweevers Wanna create an issue on `abstract-leveldown` for this and link to this issue?

**Comment by martinheidegger** [comment]
I think this fixed by now, closing the issue. Please reopen if it was premature.
