### ISSUE TITLE
Question: Is it possible to run hyperdown in the browser?

### ISSUE THREAD

**Issue by eklem** [andrewosh/hyperbeedown#3]
Hi,
I'm wondering if you think or know if it is possible to run hyperdown w/hyperdb in the browser?

**Comment by soyuka** [comment]
You have to use a correct https://github.com/random-access-storage/ and find TCP alternatives for network exchanges.

**Comment by andrewosh** [comment]
To add to what @soyuka said, hyperdown is still based on a fork of hyperdb that supports lexicographic iteration that hasn't been merged upstream (and it's unlikely that it will be merged). Just something to be aware of where when it comes to support + upstream bug fixes. 

Feel free to use it for experimenting, but I wouldn't advise using it in production right now.
